#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-System-Command
Version  : 1.119
Release  : 3
URL      : https://cpan.metacpan.org/authors/id/B/BO/BOOK/System-Command-1.119.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BO/BOOK/System-Command-1.119.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libsystem-command-perl/libsystem-command-perl_1.119-1.debian.tar.xz
Summary  : 'Object for running system commands'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-System-Command-license = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(IPC::Run)

%description
NAME
System::Command - Object for running system commands
SYNOPSIS
use System::Command;

%package dev
Summary: dev components for the perl-System-Command package.
Group: Development
Provides: perl-System-Command-devel = %{version}-%{release}

%description dev
dev components for the perl-System-Command package.


%package license
Summary: license components for the perl-System-Command package.
Group: Default

%description license
license components for the perl-System-Command package.


%prep
%setup -q -n System-Command-1.119
cd ..
%setup -q -T -D -n System-Command-1.119 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/System-Command-1.119/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-System-Command
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-System-Command/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.0/System/Command.pm
/usr/lib/perl5/vendor_perl/5.28.0/System/Command/Reaper.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/System::Command.3
/usr/share/man/man3/System::Command::Reaper.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-System-Command/LICENSE
